ALTER TABLE "scenarios" ADD COLUMN IF NOT EXISTS "gender" text;--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'female' WHERE "slug" = 'manufactured-housing-first-time-buyer';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'female' WHERE "slug" = 'manufactured-housing-retiree-downsizing';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'female' WHERE "slug" = 'manufactured-housing-single-mom-relocation';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'male' WHERE "slug" = 'manufactured-housing-investor-buyer';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'female' WHERE "slug" = 'manufactured-housing-community-lot-rent-sticker-shock';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'male' WHERE "slug" = 'manufactured-housing-community-retiree-community-fit';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'female' WHERE "slug" = 'manufactured-housing-community-existing-resident-renewal';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'male' WHERE "slug" = 'manufactured-housing-community-investor-bulk-lots';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'male' WHERE "slug" = 'auto-sales-tech-worker-upgrade';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'female' WHERE "slug" = 'auto-sales-growing-family-suv';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'male' WHERE "slug" = 'auto-sales-skeptical-negotiator';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'female' WHERE "slug" = 'auto-sales-first-car-college-student';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'female' WHERE "slug" = 'hvac-service-ac-out-in-summer';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'male' WHERE "slug" = 'hvac-service-recurring-noise-complaint';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'male' WHERE "slug" = 'hvac-service-landlord-tenant-complaint';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'female' WHERE "slug" = 'hvac-service-elderly-fixed-income';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'male' WHERE "slug" = 'hvac-sales-old-system-failing';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'female' WHERE "slug" = 'hvac-sales-new-home-buyer';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'female' WHERE "slug" = 'hvac-sales-eco-conscious-upgrade';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'male' WHERE "slug" = 'hvac-sales-competing-quotes';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'male' WHERE "slug" = 'plumbing-service-slow-drain-annoyance';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'female' WHERE "slug" = 'plumbing-service-water-heater-emergency';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'male' WHERE "slug" = 'plumbing-service-diy-attempted-repair';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'male' WHERE "slug" = 'plumbing-service-renovation-timeline-pressure';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'male' WHERE "slug" = 'financial-advisor-young-professional-starting';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'female' WHERE "slug" = 'financial-advisor-pre-retiree-anxious';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'female' WHERE "slug" = 'financial-advisor-inheritance-windfall';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'male' WHERE "slug" = 'financial-advisor-overconfident-diy-investor';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'female' WHERE "slug" = 'insurance-auto-price-shopper';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'female' WHERE "slug" = 'insurance-auto-new-driver-parent';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'male' WHERE "slug" = 'insurance-auto-post-accident-frustrated';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'female' WHERE "slug" = 'insurance-auto-bundling-opportunity';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'male' WHERE "slug" = 'real-estate-relocating-professional';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'female' WHERE "slug" = 'real-estate-downsizing-empty-nesters';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'female' WHERE "slug" = 'real-estate-first-time-buyer-anxious';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'male' WHERE "slug" = 'real-estate-investor-multi-unit';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'female' WHERE "slug" = 'apartment-rental-recent-grad';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'female' WHERE "slug" = 'apartment-rental-family-more-space';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'male' WHERE "slug" = 'apartment-rental-remote-worker-noise';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'female' WHERE "slug" = 'apartment-rental-pet-owner-restrictions';--> statement-breakpoint
UPDATE "scenarios" SET "gender" = 'female' WHERE "gender" IS NULL;--> statement-breakpoint
ALTER TABLE "scenarios" ALTER COLUMN "gender" SET NOT NULL;
